version: "2.1"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mylibrary
      MYSQL_USER: em
      MYSQL_PASSWORD: daar2021
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpadmin
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - db

  api:
    container_name: mylibrary-api
    build: ./api
    image: mylibrary-api:0.1
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "${HOME}/.m2:/root/.m2"
